# Change these first
owner: corcd # Your GitHub username
repo: charlotte # Your Github repository name

# Add your sites here
sites:
  - name: Corcd Blog
    url: https://www.corcd.xyz
  - name: Guangdianyun
    url: https://www.guangdianyun.tv
  - name: Guangdianyun Consoles
    url: https://consoles.guangdianyun.tv

assignees:
  - corcd

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: charlotte.corcd.xyz
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Charlotte
  introTitle: "**Charlotte** is a uptime monitor"
  introMessage: Powered by GitHub Actions
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
